no_mask=True

python fed_depth_mhead.py --gpu 5 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar100 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 1 --no_mask_loss $no_mask &
python fed_depth_mhead.py --gpu 5 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar100 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 0.3 --no_mask_loss $no_mask &
python fed_depth_mhead.py --gpu 5 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar10 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 1 --no_mask_loss $no_mask &
python fed_depth_mhead.py --gpu 5 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar10 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 0.3 --no_mask_loss $no_mask &
python fed_depth.py --gpu 6 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar100 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 1 --no_mask_loss $no_mask &
python fed_depth.py --gpu 6 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar100 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 0.3 --no_mask_loss $no_mask &
python fed_depth.py --gpu 6 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar10 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 1 --no_mask_loss $no_mask &
python fed_depth.py --gpu 6 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar10 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 0.3 --no_mask_loss $no_mask

# python fed_depth_mhead.py --gpu 5 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar100 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 1 --no_mask_loss $no_mask --test &
# python fed_depth_mhead.py --gpu 5 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar100 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 0.3 --no_mask_loss $no_mask --test &
# python fed_depth_mhead.py --gpu 5 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar10 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 1 --no_mask_loss $no_mask --test &
# python fed_depth_mhead.py --gpu 5 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar10 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 0.3 --no_mask_loss $no_mask --test &
# python fed_depth.py --gpu 6 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar100 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 1 --no_mask_loss $no_mask --test &
# python fed_depth.py --gpu 6 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar100 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 0.3 --no_mask_loss $no_mask --test &
# python fed_depth.py --gpu 6 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar10 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 1 --no_mask_loss $no_mask --test &
# python fed_depth.py --gpu 6 --model preresnet20 --batch 128 --iters 500 --seed 1 --data Cifar10 --sufficient 1 --width_scale 1 --pd_nuser 100 --pr_nuser 10 --wk_iters 10 --no_track_stat --lr 0.01 --lr_sch cos --additional AAA --partition_method dir --alpha 0.3 --no_mask_loss $no_mask --test 